### ISSUE TITLE
Start min the first time:  no such file or directory

### ISSUE THREAD

**Issue by m040601** [a-h/min#1]
Thanks for your work on this tool.
I'm testing several clients for gemini.
So far I like it. Simple, uncomplicated text formats for bookmarks/history, good colors and you seem to have a good understanding of what sane and good keyboard defaults are.

Nice if you could support the XDG standard and have min
put its stuff in ~/.config/min instead of  the home dir.

Nice, and very important, that you thought of releasing the precompiled binaries.

The first time one tries to run it, it doesnt' start, it complains:

`Error loading history: open /home/USER/.min/history.tsv: no such file or directory
`

One needs to first explicitly create the config dir

`mkdir ~/.min`

The program then runs and automatically creates the config.ini and history.tsv

Seems to be working fine afterwards.
Testing both in x64 and armv6 (raspberry pi)

Additionally, on my Raspberry Pi 1.2 b (armv7h):

file ./min

`ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=-6cHE7WyQ2x-ZvJ4Krdt/L5jZJZp3qJ8WtnI_3DtH/YGvvPxg3wqwhoqYkUKRz/Mp6_WOvgzmbR9kI0W9dA, strippedcat clorec
`

Please clarify in the README's that the binary you release as "armv6" should be ok (as I presume) to run on all raspberry pi's (zero, 1, 2, 3) except the PI 4.

**Comment by a-h** [comment]
Thanks so much for testing it out! I've got a few pis around the house including a Pi 4, so I'll give it a go on that and validate it.

I've fixed the configuration directory issue, thanks for pointing that out.

**Comment by a-h** [comment]
I've just tested it on a Raspberry Pi Zero W (Raspbian) and Raspberry Pi 4 (running Ubuntu) that I have running around the house, both required the ARM v6 build. I've updated the README to clarify that.
